# Generated by Django 3.0.8 on 2020-07-30 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_title', models.CharField(max_length=30, unique=True, verbose_name='分类')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_title', models.CharField(max_length=30, unique=True, verbose_name='板块')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '板块 ',
                'verbose_name_plural': '板块 ',
            },
        ),
        migrations.CreateModel(
            name='WebSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=200, verbose_name='网站名称')),
                ('web_logo_big', models.ImageField(blank=True, default='logos/logo_big.png', null=True, upload_to='logos', verbose_name='网站logo大图')),
                ('web_logo', models.ImageField(blank=True, default='logos/logo_mix.png', null=True, upload_to='logos', verbose_name='网站logo')),
                ('domain', models.URLField(max_length=1000, verbose_name='网站地址')),
                ('site_description', models.TextField(default='', max_length=1000, verbose_name='网站描述')),
                ('site_seo_description', models.TextField(default='', max_length=3000, verbose_name='网站SEO描述')),
                ('site_keywords', models.TextField(default='', max_length=1000, verbose_name='网站关键字')),
                ('github', models.URLField(max_length=1000, verbose_name='项目git地址')),
                ('author', models.CharField(default='', max_length=100, verbose_name='作者')),
                ('authorSite', models.URLField(max_length=1000, verbose_name='作者主页')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='网站名称')),
                ('logo', models.ImageField(blank=True, default='default.png', null=True, upload_to='upload', verbose_name='Logo')),
                ('url', models.URLField(unique=True, verbose_name='链接')),
                ('info', models.CharField(max_length=100, verbose_name='简介')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav.Archive', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
            },
        ),
        migrations.AddField(
            model_name='archive',
            name='A_plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav.Plate', verbose_name='所属板块'),
        ),
    ]
